// Generated by CoffeeScript 1.8.0
(function() {
  var CraneElements;

  CraneElements = (function() {
    CraneElements.prototype.crane = null;

    CraneElements.prototype.NAMEPARENT = "noCommonElements";

    function CraneElements() {
      this.crane = document.createElement("div");
      this.crane.setAttribute("id", "elementsTheCrane");
      document.getElementById(this.NAMEPARENT).appendChild(this.crane);
      this.distance();
    }

    CraneElements.prototype.distance = function() {
      var bigElementDistance, distance, div, divSlider, smallElementDistance, strong;
      smallElementDistance = new Item("img", ["src", "class", "alt"], ["images/bulb.png", "img-responsive", "bulb"], null, false, null);
      strong = new Item("strong", [], [], "How much distance do you want?", false, null);
      divSlider = new Item("div", ["id", "class"], ["slider-distance", "slider slider-distance"], null, false, null);
      div = new Item("div", ["class"], ["slidera"], null, true, [divSlider]);
      bigElementDistance = new Item("div", ["class"], ["form-group"], null, true, [strong, div]);
      distance = new Element();
      distance.specialElement([smallElementDistance], [bigElementDistance]);
      this.crane.appendChild(distance.div);
      $('.slider-distance').noUiSlider({
        start: 0,
        step: 1,
        connect: "lower",
        range: {
          'min': [0],
          'max': [100]
        }
      });
      $(".slider-distance").noUiSlider_pips({
        mode: 'count',
        values: 5,
        density: 2,
        stepped: true,
        format: wNumb({
          postfix: 'cm'
        })
      });
      return $(".slider").Link('lower').to("-inline-<div class=\"tooltipe\"></div>", function(value) {
        return $(this).html("<span>" + Math.floor(value) + "</span>");
      });
    };

    CraneElements.prototype.remove = function() {
      return this.crane.parentNode.removeChild(this.crane);
    };

    return CraneElements;

  })();

  window.CraneElements = CraneElements;

}).call(this);
