// Generated by CoffeeScript 1.8.0
(function() {
  var CraneElements;

  CraneElements = (function() {
    CraneElements.prototype.crane = null;

    CraneElements.prototype.NAMEPARENT = "noCommonElements";

    CraneElements.prototype.wsData = null;

    function CraneElements(wsData) {
      this.wsData = wsData;
      this.crane = document.createElement("div");
      this.crane.setAttribute("id", "elementsTheCrane");
      document.getElementById(this.NAMEPARENT).appendChild(this.crane);
      this.distance();
    }

    CraneElements.prototype.distance = function() {
      var bigElementDistance, distance, div, divSlider, smallElementDistance, strong;
      smallElementDistance = new Item("img", ["src", "class", "alt"], ["images/crane.png", "img-responsive", "crane image"], null, false, null);
      strong = new Item("strong", [], [], "How much distance do you want?", false, null);
      divSlider = new Item("div", ["id", "class"], ["slider-distance", "slider slider-distance"], null, false, null);
      div = new Item("div", ["class"], ["slidera"], null, true, [divSlider]);
      bigElementDistance = new Item("div", ["class"], ["form-group"], null, true, [strong, div]);
      distance = new Element();
      distance.specialElement([smallElementDistance], [bigElementDistance]);
      this.crane.appendChild(distance.div);
      return new Slider('slider-distance', 0, 1, [0], [100], 5, 2, 'cm');
    };

    CraneElements.prototype.remove = function() {
      return this.crane.parentNode.removeChild(this.crane);
    };

    CraneElements.prototype.sendDistance = function() {
      var auxDistance;
      auxDistance = parseInt($(".slider-distance").val());
      if (auxDistance !== 0) {
        return this.wsData.sendActuatorChange('WeightTrip', auxDistance.toString());
      }
    };

    CraneElements.prototype.disable = function() {
      return $('.slider-distance').attr('disabled', 'disabled');
    };

    CraneElements.prototype.enable = function() {
      return $('.slider-distance').removeAttr('disabled');
    };

    return CraneElements;

  })();

  window.CraneElements = CraneElements;

}).call(this);
