// Generated by CoffeeScript 1.8.0
(function() {
  var Element;

  Element = (function() {
    Element.prototype.div = null;

    function Element() {
      this.div = document.createElement("div");
    }

    Element.prototype.standardElement = function(args) {
      var item, _i, _len, _results;
      this.div.setAttribute("class", "row");
      _results = [];
      for (_i = 0, _len = args.length; _i < _len; _i++) {
        item = args[_i];
        _results.push(this.div.appendChild(this.createMyElement(this.div, item)));
      }
      return _results;
    };

    Element.prototype.specialElement = function(smallArgs, bigArgs) {
      this.div.setAttribute("class", "row vertical-align");
      this.div.appendChild(this.smallElement(smallArgs));
      return this.div.appendChild(this.bigElement(bigArgs));
    };

    Element.prototype.smallElement = function(args) {
      var div, item, _i, _len;
      div = document.createElement("div");
      div.setAttribute("class", "col-xs-3 col-lg-3");
      for (_i = 0, _len = args.length; _i < _len; _i++) {
        item = args[_i];
        this.createMyElement(div, item);
      }
      return div;
    };

    Element.prototype.bigElement = function(args) {
      var div, form, item, _i, _len;
      div = document.createElement("div");
      div.setAttribute("class", "col-xs-9 col-lg-9");
      form = document.createElement("form");
      form.setAttribute("class", "form");
      form.setAttribute("role", "form");
      form.setAttribute("autocomplete", "off");
      div.appendChild(form);
      for (_i = 0, _len = args.length; _i < _len; _i++) {
        item = args[_i];
        this.createMyElement(form, item);
      }
      return div;
    };

    Element.prototype.createMyElement = function(parent, item) {
      var child, element, i, nAttr, _i, _j, _len, _len1, _ref, _ref1;
      element = document.createElement(item.typeElement);
      _ref = item.nameAttr;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        nAttr = _ref[i];
        element.setAttribute(nAttr, item.dataAttr[i]);
      }
      if (item.text !== null) {
        element.appendChild(document.createTextNode(item.text));
      }
      if (item.parent) {
        _ref1 = item.child;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          child = _ref1[_j];
          this.createMyElement(element, child);
        }
      }
      return parent.appendChild(element);
    };

    return Element;

  })();

  window.Element = Element;

}).call(this);
