// Generated by CoffeeScript 1.8.0
(function() {
  var Esd;

  Esd = (function() {
    Esd.prototype.canvas = null;

    Esd.prototype.img = null;

    Esd.prototype.width = null;

    Esd.prototype.height = null;

    Esd.prototype.resizeActive = null;

    Esd.prototype.plot = null;

    function Esd(idCanvas, img, lumens) {
      var a;
      this.canvas = document.getElementById(idCanvas);
      this.img = document.getElementById(img);
      this.canvas.width = this.img.width;
      this.canvas.height = this.img.height;
      a = document.getElementById(lumens);

      /*
      if @img.complete  #check if image was already loaded by the browser
          @drawImageInCanvas()
      else 
          @img.onload  = => 
              console.log "caa"
              @drawImageInCanvas()
              new Plot()
       */
      this.drawImageInCanvas();
      this.plot = new Plot();
      sliders();
      window.addEventListener("resize", (function(_this) {
        return function() {
          if (_this.resizeActive) {
            clearTimeout(_this.resizeActive);
          }
          return _this.resizeActive = setTimeout(function() {
            _this.drawImageInCanvas();
            return _this.plot.resizeEvent();
          }, 250);
        };
      })(this));
    }

    Esd.prototype.drawImageInCanvas = function() {
      var a, ctx;
      this.width = this.canvas.width = this.img.width;
      this.height = this.canvas.height = this.img.height;
      ctx = this.canvas.getContext("2d");
      a = window.innerHeight - document.getElementById("panel-elements").offsetHeight;
      a = a - 20;
      document.getElementById("adapt-to-height").setAttribute("style", "height:" + a + "px");
      ctx.font = Math.floor(this.width * 0.05) + "px monospace";
      ctx.fillText("Amps", this.width / 11, 8 * (this.height / 20));
      ctx.fillText("Volts", this.width / 11, 11 * (this.height / 20));
      ctx.fillText("Joules", this.width / 11, 14 * (this.height / 20));
      ctx.fillText("Charging", 3.5 * (this.width / 11), 5 * (this.height / 20));
      return ctx.fillText("Discharging", 6.5 * (this.width / 11), 5 * (this.height / 20));
    };

    return Esd;

  })();

  window.Esd = Esd;

}).call(this);
