// Generated by CoffeeScript 1.8.0
(function() {
  var Init;

  Init = (function() {
    Init.prototype.plot = null;

    Init.prototype.resizeActive = null;

    function Init(idCanvas, img) {
      console.log("lalalalala");
      this.plot = new Plot(idCanvas, img);
      sliders();
      window.addEventListener("resize", (function(_this) {
        return function() {
          if (_this.resizeActive) {
            clearTimeout(_this.resizeActive);
          }
          return _this.resizeActive = setTimeout(function() {
            _this.esd.drawImageInCanvas();
            return _this.plot.resizeEvent();
          }, 250);
        };
      })(this));
    }

    return Init;

  })();

  window.Init = Init;

}).call(this);
