// Generated by CoffeeScript 1.8.0
(function() {
  var Part;

  Part = (function() {
    Part.prototype.INFOMODAL = '#infoModal';

    Part.prototype.INFOMODALTITLE = '#infoModalTitle';

    Part.prototype.INFOMODALBODY = '#infoModalBody';

    Part.prototype.wsData = null;

    function Part(wsData) {
      this.wsData = wsData;
    }

    Part.prototype.modalText = function(title, body) {
      $(this.INFOMODALTITLE).empty();
      $(this.INFOMODALBODY).empty();
      $(this.INFOMODALTITLE).append('<p>' + title + '</p>');
      return $(this.INFOMODALBODY).append('<p>' + body + '</p>');
    };

    return Part;

  })();

  window.Part = Part;

}).call(this);
