// Generated by CoffeeScript 1.8.0
(function() {
  var Plot;

  Plot = (function() {
    Plot.prototype.resizeActive = null;

    Plot.prototype.data = null;

    Plot.prototype.options = null;

    Plot.prototype.chart = null;

    function Plot() {
      this.resize();
      google.setOnLoadCallback(this.drawChart());
      window.addEventListener("resize", (function(_this) {
        return function() {
          if (_this.resizeActive) {
            clearTimeout(_this.resizeActive);
          }
          return _this.resizeActive = setTimeout(function() {
            _this.resize();
            return _this.chart.draw(_this.data, _this.options);
          }, 500);
        };
      })(this));
    }

    Plot.prototype.resize = function() {
      var a;
      a = document.getElementById("div_formula_col").offsetHeight - document.getElementById("experiment-real-time-data").offsetHeight - 90;
      a = a - 20;
      return document.getElementById("chart_div").setAttribute("style", "height:" + a + "px");
    };

    Plot.prototype.drawChart = function() {
      this.data = google.visualization.arrayToDataTable([['Year', 'Sales', 'Expenses'], ['2004', 1000, 400], ['2005', 1170, 460], ['2006', 660, 1120], ['2007', 1030, 540]]);
      this.options = {
        title: 'Company Performance'
      };
      this.chart = new google.visualization.LineChart(document.getElementById('chart_div'));
      return this.chart.draw(this.data, this.options);
    };

    return Plot;

  })();

  window.Plot = Plot;

}).call(this);
