// Generated by CoffeeScript 1.8.0
(function() {
  var Plot;

  Plot = (function() {
    function Plot() {
      google.load("visualization", "1", {
        packages: ["corechart"]
      });
      google.setOnLoadCallback(this.drawChart);
    }

    Plot.prototype.drawChart = function() {
      var chart, data, options;
      data = google.visualization.arrayToDataTable([['Year', 'Sales', 'Expenses'], ['2004', 1000, 400], ['2005', 1170, 460], ['2006', 660, 1120], ['2007', 1030, 540]]);
      options = {
        title: 'Company Performance'
      };
      chart = new google.visualization.LineChart(document.getElementById('chart_div'));
      return chart.draw(data, options);
    };

    return Plot;

  })();

  window.Plot = Plot;

}).call(this);
