// Generated by CoffeeScript 1.8.0
(function() {
  var sliders;

  window.sliders = sliders = function() {

    /*
    $('.slider-weigth').noUiSlider({
      start: 0,
      step: 1,
      connect: "lower",
      range: {
        'min': [0],
        'max': [50]
      }
    })
     */
    $(".slider-weigth").noUiSlider_pips({
      mode: 'count',
      values: 6,
      density: 3,
      stepped: true,
      format: wNumb({
        postfix: 'cm'
      })
    });
    $(".slider-weigth").attr('disabled', 'disabled');
    return $(".slider").Link('lower').to("-inline-<div class=\"tooltipe\"></div>", function(value) {
      return $(this).html("<span>" + Math.floor(value) + "</span>");
    });
  };

}).call(this);
