// Generated by CoffeeScript 1.8.0
(function() {
  var Item;

  Item = (function() {
    Item.prototype.typeElement = null;

    Item.prototype.nameAttr = [];

    Item.prototype.dataAttr = [];

    Item.prototype.text = null;

    Item.prototype.parent = false;

    Item.prototype.child = null;

    function Item(typeElement, nameAttr, dataAttr, text, parent, child) {
      this.typeElement = typeElement;
      this.nameAttr = nameAttr;
      this.dataAttr = dataAttr;
      this.text = text;
      this.parent = parent;
      this.child = child;
    }

    return Item;

  })();

  window.Item = Item;

}).call(this);
