// Generated by CoffeeScript 1.8.0
(function() {
  var Formula;

  Formula = (function() {
    Formula.prototype.numA = 0;

    Formula.prototype.numB = 0;

    Formula.prototype.numC = 0;

    Formula.prototype.operatorAandB = null;

    Formula.prototype.operatorBandC = null;

    Formula.prototype.div = null;

    function Formula(div) {
      this.div = div;
      this.createFormula();
    }

    Formula.prototype.createFormula = function() {};

    return Formula;

  })();

}).call(this);
